Devika/#1y2w2db auth setup
chibDevika/boilerplate-fe pull request #1
Opened 2022-01-11 09:05 UTC by chibDevika

2022-01-11 16:07 UTC, shubham-gup requested changes

2022-01-11 16:07 UTC, shubham-gup commented on package.json
> +    "firebase": "^9.6.2",
Why do we need firebase?

2022-01-11 16:07 UTC, shubham-gup commented on package.json
> +    "redux-thunk": "^2.4.1",
Why do we need thunk?

2022-01-11 16:07 UTC, shubham-gup commented on package.json
> +    "source-map-loader": "^1.0.0"
Why do we need this?

2022-01-11 16:07 UTC, shubham-gup commented on src/.eslintrc.js
> +};
There is already eslint config present, why create a new one? Also, why disable this rule?

2022-01-11 16:07 UTC, shubham-gup commented on src/Signin.jsx
> +  '775627361104-rldutbneq1qi1floukp4sgauct6qg4at.apps.googleusercontent.com';
Is it safe to put secret codes like this and push them to github, open source repo?

2022-01-11 16:07 UTC, shubham-gup commented on src/Signin.jsx
> +    </div>
Do we need this `div`?

2022-01-11 16:07 UTC, shubham-gup commented on src/Signout.jsx
> +  '775627361104-rldutbneq1qi1floukp4sgauct6qg4at.apps.googleusercontent.com';
Secret code?

2022-01-11 16:07 UTC, shubham-gup commented on src/index.js
> +    {/* </Provider> */}
Can remove code if we are not using it?

2022-01-11 16:07 UTC, shubham-gup commented on src/refreshToken.js
> +};
How will this method behave? Also, how will this `timeout` behave?
Should we create a separate file for this? What kind of method is this, can it be somewhere else?

2022-01-11 16:07 UTC, shubham-gup commented on src/App.js
> +      <Signout />
Should we render both signin and signout together?

2022-01-11 16:49 UTC, chibDevika commented on src/index.js
> +    {/* </Provider> */}
I'll remove

2022-01-11 16:51 UTC, chibDevika commented on src/Signout.jsx
> +  '775627361104-rldutbneq1qi1floukp4sgauct6qg4at.apps.googleusercontent.com';
I was facing some issues with that. Will implement by next pr.

2022-01-11 16:52 UTC, chibDevika commented on src/Signin.jsx
> +    </div>
Yeah, it comes with the package. We need it to set the parameters.

2022-01-11 16:52 UTC, chibDevika commented on src/Signin.jsx
> +  '775627361104-rldutbneq1qi1floukp4sgauct6qg4at.apps.googleusercontent.com';
I was facing some issues with that. Will implement by next pr.

2022-01-11 16:54 UTC, chibDevika commented on src/.eslintrc.js
> +};
I had some errors in the console so I was following a recommended fix that's why created this file. Later when I tried to remove it and push the code, there were a lot of conflicts so I left it as it is

2022-01-11 16:55 UTC, chibDevika commented on package.json
> +    "source-map-loader": "^1.0.0"
There's load map error in my console, I was trying to fix it by following recommended fixes

2022-01-11 16:56 UTC, chibDevika commented on package.json
> +    "redux-thunk": "^2.4.1",
I tried to understand how to use redux, but felt like it'll take time. Have parked it for now, I'll remove this.

2022-01-11 16:58 UTC, chibDevika commented on package.json
> +    "firebase": "^9.6.2",
I meant to remove it. It's done now

2022-01-12 05:30 UTC, shubham-gup commented on src/.eslintrc.js
> +};
Why were there conflicts in your own code?

2022-01-12 05:31 UTC, shubham-gup commented on package.json
> +    "source-map-loader": "^1.0.0"
Let's discuss this in our sync

2022-01-12 05:31 UTC, shubham-gup commented on src/Signin.jsx
> +    </div>
The wrapper `div` I am talking about

2022-01-12 06:02 UTC, chibDevika commented on src/Signin.jsx
> +    </div>
No it's serving any special purpose I suppose. I'll remove it.

2022-01-12 10:30 UTC, shubham-gup requested changes

2022-01-12 10:30 UTC, shubham-gup commented on src/App.css
> +  justify-content: center;
Should we use px values? Will these scale as per screen resolution?

2022-01-12 10:30 UTC, shubham-gup commented on src/App.js
> +      </div>
Is name `RoutesDir` indicative of what the component is about?
Also, class name convention.

2022-01-12 10:30 UTC, shubham-gup commented on src/Components/LandingPage.jsx
> +          style={{ marginTop: '100px' }}
`px` values?

2022-01-12 10:30 UTC, shubham-gup commented on src/Components/RoutesDir.js
> +    </div>
Is there a need to wrap this in `div`?

2022-01-12 10:30 UTC, shubham-gup commented on src/Components/Signin.jsx
> +        // responseType="id_token"
What does this do?

2022-01-12 10:30 UTC, shubham-gup commented on src/refreshToken.js
> +};
Do we need this now?

2022-01-12 11:33 UTC, chibDevika commented on src/refreshToken.js
> +};
I texted you about it. I wasn't able to fix the issue with logout. Maybe you could check it out once?

2022-01-12 11:34 UTC, chibDevika commented on src/Components/Signin.jsx
> +        // responseType="id_token"
This component isn't being used right now. I tried to delete it but it raised some conflicts. Will remove the component soon

2022-01-12 11:36 UTC, chibDevika commented on src/Components/RoutesDir.js
> +    </div>
No it isn't serving any purpose, I'll remove that

2022-01-12 11:41 UTC, chibDevika commented on src/App.js
> +      </div>
Routes seemed more appropriate but I thought since its a different component already, I should change this.
I'll update the name convention to camelCase

2022-01-12 11:42 UTC, chibDevika commented on src/.eslintrc.js
> +};
I'll discuss it with you in next stand up

2022-01-12 11:42 UTC, chibDevika commented on src/refreshToken.js
> +};
Still working on this

2022-01-12 11:43 UTC, chibDevika commented on src/App.css
> +  justify-content: center;
No these are static, they won't scale. I'll change to %

2022-01-12 11:44 UTC, chibDevika commented on src/Components/LandingPage.jsx
> +          style={{ marginTop: '100px' }}
Will change to %

2022-01-12 12:06 UTC, shubham-gup commented on src/App.css
> +  justify-content: center;
Can we change it to anything else except %?

2022-01-12 12:06 UTC, shubham-gup commented on src/App.js
> +      </div>
The case is fine, I think name `Routes` seem better.

2022-01-12 17:20 UTC, chibDevika commented on src/App.css
> +  justify-content: center;
Yes changed it to em. They're also relative to the page

2022-01-12 17:21 UTC, chibDevika commented on src/App.js
> +      </div>
Since Routes is already being imported in this routesDir, it gave an error

2022-01-13 05:28 UTC, shubham-gup commented on src/Components/LandingPage.jsx
> +          style={{ marginTop: '100px' }}
em right?

2022-01-13 11:45 UTC, merged