Devika/#1yzdae4
chibDevika/boilerplate-fe pull request #3
Opened 2022-01-20 06:14 UTC by chibDevika

2022-01-20 11:47 UTC, shubham-gup requested changes

2022-01-20 11:47 UTC, shubham-gup commented on package.json
> +    "date-fns": "^2.0.0-beta.5",
This dependency is for?

2022-01-20 11:47 UTC, shubham-gup commented on src/App.css
> +  margin-top: 45em;
Should we use `rem` here?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/Calendar.jsx
> +  const eventComponent = useCallback(() => {
Can use meaningful method names? This doesn't tell me what this method does.

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/Calendar.jsx
> +        });
Can we create `event` array by mapping over data?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/Calendar.jsx
> +        style={{ height: 600 }}
Let's avoid inline styles, also. Is this responsive?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/DateTimePicker.jsx
> +    <LocalizationProvider dateAdapter={MomentUtils}>
Why do we need this?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/DateTimePicker.jsx
> +        }}
Should we `destructure` props?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/HomePage.jsx
> +  };
Should this be `memoized`?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/HomePage.jsx
> +            updateDate={start => setStartDate(moment(start))} />
Should we pass a method here instead of inline function?

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/HomePage.jsx
> +          }}
Let's avoid inline styles.

2022-01-20 11:47 UTC, shubham-gup commented on src/Components/HomePage.jsx
> +            }}
Let's avoid adding inline functions and add methods reference.
You can read about how javascript references and functions work to better understand it. We can discuss this further if you feel like it.

2022-01-20 17:55 UTC, chibDevika commented on package.json
> +    "date-fns": "^2.0.0-beta.5",
It was extra, removed it now

2022-01-20 17:58 UTC, chibDevika commented on src/Components/Calendar.jsx
> +  const eventComponent = useCallback(() => {
changed it

2022-01-20 18:21 UTC, chibDevika commented on src/App.css
> +  margin-top: 45em;
This is responsive only. Why shouldn't we use em?

2022-01-20 18:23 UTC, chibDevika commented on src/Components/Calendar.jsx
> +        });
Mapping over data as in?

2022-01-20 18:44 UTC, chibDevika commented on src/Components/Calendar.jsx
> +        style={{ height: 600 }}
This was the calendar component from the react-big-calendar package. It is responsive

2022-01-20 18:58 UTC, chibDevika commented on src/Components/DateTimePicker.jsx
> +    <LocalizationProvider dateAdapter={MomentUtils}>
I'm not sure but I think since we are using the moment package for date management. And a localisation provider would set it according to a region

2022-01-21 05:58 UTC, chibDevika commented on src/Components/HomePage.jsx
> +  };
I don't think so because this will be called only when save button is hit, and that is to be hit on the entry of new leave only

2022-01-21 05:59 UTC, chibDevika commented on src/Components/HomePage.jsx
> +          }}
Fixed it

2022-01-24 11:52 UTC, merged