Session mgmt
chibDevika/boilerplate-fe pull request #4
Opened 2022-01-22 12:02 UTC by chibDevika

2022-01-23 07:03 UTC, shubham-gup requested changes

2022-01-23 07:03 UTC, shubham-gup commented on src/Components/HomePage.jsx
> +  };
Should this be memoized?

2022-01-23 07:03 UTC, shubham-gup commented on src/Components/HomePage.jsx
> +            updateDate={end => setEndDate(moment(end))}
Let's avoid inline methods?

2022-01-23 07:03 UTC, shubham-gup commented on src/Components/LandingPage.jsx
> +        username: "testUser",
`testUser`?

2022-01-23 07:03 UTC, shubham-gup commented on src/Components/LandingPage.jsx
> +      console.log(res);
Let's not leave console log in code after testing?

2022-01-23 07:03 UTC, shubham-gup commented on src/Components/LandingPage.jsx
> +  };
Should this be memoized?

2022-01-23 08:32 UTC, chibDevika commented on src/App.css
> +  margin-right: 30%;
yes done

2022-01-23 08:32 UTC, chibDevika commented on src/App.css
> +  height: 200;
yes done

2022-01-23 08:33 UTC, chibDevika commented on src/Components/Calendar.jsx
> +        style={{ height: 600 }}
the component doesn't work if I remove it, it's a property of the component I think

2022-01-23 08:36 UTC, chibDevika commented on src/Components/Calendar.jsx
> +    if (localStorage.getItem('access_token')) {
yes, fixed it

2022-01-23 08:39 UTC, chibDevika commented on src/Components/LandingPage.jsx
> +      console.log(res);
removed it

2022-01-23 08:41 UTC, chibDevika commented on src/Components/LandingPage.jsx
> +  };
I had missed it. done now

2022-01-23 08:43 UTC, chibDevika commented on src/Components/LandingPage.jsx
> +        username: "testUser",
I had missed it. changed it

2022-01-23 08:43 UTC, chibDevika commented on src/Components/HomePage.jsx
> +  };
done

2022-01-23 08:54 UTC, chibDevika commented on src/Components/HomePage.jsx
> +            updateDate={end => setEndDate(moment(end))}
I've changed most of them, but some changes won't come in effect from css file.

2022-01-24 07:57 UTC, shubham-gup requested changes

2022-01-24 07:57 UTC, shubham-gup commented on src/App.css
> +  background-color: #e6e6e6;
Should we create constants for colors?

2022-01-24 07:57 UTC, shubham-gup commented on src/Components/Calendar.jsx
> +  };
Should we warp these with `useCallback`?

2022-01-24 07:57 UTC, shubham-gup commented on src/Components/Calendar.jsx
> +        style={{ height: 600 }}
Can we do it by a class?

2022-01-24 08:28 UTC, chibDevika commented on src/Components/Calendar.jsx
> +  };
done

2022-01-24 08:31 UTC, chibDevika commented on src/Components/Calendar.jsx
> +        style={{ height: 600 }}
It didn't work, I tried that

2022-01-24 08:36 UTC, chibDevika commented on src/App.css
> +  background-color: #e6e6e6;
done

2022-01-24 11:52 UTC, merged